name: Changelog CI
description: This is an action that commits on a release pull request with the changelog
author: Maksudul Haque
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  changelog_filename:
    description: 'Name of the changelog file if not provided defaults to CHANGELOG.md'
    required: false
    default: 'CHANGELOG.md'
  config_file:
    description: 'Location of the config JSON file'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
