group_config:
  # Use PR labels to add an annotation to the changelog.
  # This list of labels is from https://keepachangelog.com/en/1.0.0/#types
  # They are sensible defaults, but you may change them if your repo uses different labels.

  # Added for new features.
  - title: Added
    labels:
      - added

  # Changed for changes in existing functionality.
  - title: Changed
    labels:
      - changed

  # Deprecated for soon-to-be removed features.
  - title: Deprecated
    labels:
      - deprecated

  # Removed for now removed features.
  - title: Removed
    labels:
      - removed

  # Fixed for any bug fixes.
  - title: Fixed
    labels:
      - fixed

  # Security in case of vulnerabilities.
  - title: Security
    labels:
      - security
