# Config for automated changelog generation using JonathanAquino/changelog-pr.

# PRs with this label won't be added to the changelog.
skip_changelog_label: skip-changelog

# These patterns will be removed from the PR title (case-insensitive).
pr_title_removal_regex: '\[wip\]\s*'

# Use PR labels to add an annotation to the changelog. You may change these
# if your repo uses different labels. The important thing is that they
# distinguish between breaking changes, features/enhancements, and bug fixes.
pr_labels:
  # You might want to comment out this label for UI repos.
  - breaking-changes
  - new-feature
  - enhancement
  - bug
  # Add a description to this label on GitHub: "Changes to algorithms or methodologies"
  - implementation-changes
  # If you modify any of these labels, please also update the labels in verify-pr-labels.yaml
