name: Changelog PR

on:
  push:
    branches:
      # Trigger the action when a PR is merged to master. Change this to "main" if you are using main.
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Run Changelog PR
        uses: JonathanAquino/changelog-pr     # Normally it is a good idea to append a version here like @v0.9.0
        with:
          changelog_filename: CHANGELOG.md
          config_file: changelog-pr-config.yml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
