name: Changelog PR

on:
  push:
    branches:
      # Run this action when the following branch is pushed to, typically master or main.
      # Keep this in sync with with.branch below.
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Run Changelog PR
        uses: JonathanAquino/changelog-pr@main
        with:
          changelog_filename: CHANGELOG.md
          config_file: changelog-pr-config.yaml
          # Commit the changelog to this branch, typically master or main.
          # Keep this in sync with on.push.branches above.
          branch: main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
