name: Changelog PR

on:
  push:
    branches:
      # Run this action when the default branch is pushed to (typically master or main).
      - ${{ github.event.repository.default_branch }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Run Changelog PR
        uses: JonathanAquino/changelog-pr@main
        with:
          changelog_filename: CHANGELOG.md
          config_file: changelog-pr-config.yaml
          # Commit the changelog to the default branch (typically master or main).
          branch: ${{ github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
