# This workflow will be verify that all PRs have a valid changelog label
# before they can be merged. This is a prerequisite for the changelog-pr.yaml workflow.

name: Verify PR labels
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check_pr_labels:
    runs-on: ubuntu-latest
    name: Verify that the PR has a valid label
    steps:
      - name: Verify PR label action
        uses: JonathanAquino/verify-pr-label-action@master
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'skip-changelog, breaking-changes, new-feature, enhancement, bug, implementation-changes'
          pull-request-number: '${{ github.event.pull_request.number }}'
          disable-reviews: true
